# Subsistema I2C: obligatorio para hablar con el BMP280
CONFIG_I2C=y

# Necesario para que printk()/printf() puedan imprimir floats (%f)
CONFIG_CBPRINTF_FP_SUPPORT=y

# Sistema de logging: la libreria reporta errores via LOG_ERR/LOG_INF
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Margen de pila algo mayor (logging + floats + printk)
CONFIG_MAIN_STACK_SIZE=2048
